### ISSUE TITLE
Need to restart resource before it works.

### ISSUE THREAD

**Issue by Lannebro** [EgoPvP/erp_towscript#6]
Gooday.  As stated. I need to restart this resource before it works. Have had simular problems with others resources. Always been 1-2 that dont mix. Now however, i cant find the reason. Ideás?

**Comment by ZockerBoysHD** [comment]
What means "it doesnt work" doesnt it give u any errors, any crashes etc?

Which Artifact ad ESX version ur running?

**Comment by Lannebro** [comment]
Running esx 1.3.5 legacy. I need to restart it while in game. I get no errors. 

Joining game, getting a flatbed, command /tow. (No vehicle to tow) 

Restarting resource while in game, works perfectly with /tow.

**Comment by Manta95** [comment]
Hi, I have the exact same problem on ESX 1.1 with Onesync, even when I put "restart er_towscript" at the end of the server.cfg (even with "ensure erp_towscript"... 

I will try to integrate the code directly in esx_mechanicjob to see if it's better...

**Comment by Manta95** [comment]
I find the solution : 

Replace from line 63 to 68 with this : 

            local coordA = GetEntityCoords(playerped, 1)
            local coordB = GetOffsetFromEntityInWorldCoords(playerped, 0.0, Config.VehicleRange, 0.0)
            local targetVehicle = ESX.Game.GetVehicleInDirection()
	    local isVehicleTow = IsVehicleModel(vehicle, towmodel)

            if vehicleOnTowTruck == 0 or vehicleOnTowTruck == nil then
                
                    if targetVehicle ~= 0 then

**Comment by Lannebro** [comment]
Will check it out, thx.

**Comment by Lannebro** [comment]
Works like a charm. For me this was line 68-75. Be sure to check this out before closing this thread @ZockerBoysHD

**Comment by ZockerBoysHD** [comment]
> Running esx 1.3.5 legacy. I need to restart it while in game. I get no errors.
> 
> Joining game, getting a flatbed, command /tow. (No vehicle to tow)
> 
> Restarting resource while in game, works perfectly with /tow.

1.3 is NOT legacy / the original one. the original ended in 1.1 or 1.2 i believe.

**Comment by ZockerBoysHD** [comment]
> I find the solution :
> 
> Replace from line 63 to 68 with this :
> 
> ```
>         local coordA = GetEntityCoords(playerped, 1)
>         local coordB = GetOffsetFromEntityInWorldCoords(playerped, 0.0, Config.VehicleRange, 0.0)
>         local targetVehicle = ESX.Game.GetVehicleInDirection()
>     local isVehicleTow = IsVehicleModel(vehicle, towmodel)
> 
>         if vehicleOnTowTruck == 0 or vehicleOnTowTruck == nil then
>             
>                 if targetVehicle ~= 0 then
> ```

i guess the problem is with the raycasting of the vehicles in the direction ur looking.

Also  `local isVehicleTow = IsVehicleModel(vehicle, towmodel)` was never even inside my code. I do the check if ur using a Tow vehicle way before getting the coords.  Also if ur using ESX's method to raycast, you dont need coordA and B.

I dont know why it errors out for you cause for me it worked every time i tried it so far. Imma go redo it tho cause yeah, ESX does have functions for this but i wanted to kinda be Standalone, which i am by using my own functions and not relying on any framework.  the ESX stuff is only optional so far and not even needed for operation.


Also im sorry to answer that late, i was relly busy for the past few weeks <3

**Comment by ZockerBoysHD** [comment]
If you could check the Current version which is online and report back to me,  i would love you guys <3
Again, for me it works everytime. No matter if i start mid-game or with a server start

**Comment by ZockerBoysHD** [comment]
Stale
